### ISSUE TITLE
false positive with boost-1.69.0

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#10]
Hello, while working on this: https://pagure.io/fedora-localization-statistics

I notice false positives with boost-1.69.0

```
[
   {
      'filemask':'libs/*/meta/libraries.json',
      'file_format':'json'
   },
   {
      'filemask':'tools/build/example/gettext/*.po',
      'file_format':'po'
   }
]
```

There is no json translations.

Files: 
[files.txt](https://github.com/WeblateOrg/translation-finder/files/3124942/files.txt)

Upstream sources: https://dl.bintray.com/boostorg/release/1.69.0/source/

Thanks a lot for your help!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Thanks for doing all this testing, this is really valuable feedback and helps to improve detection accuracy.

**Comment by Jibec** [comment]
You are really welcome, your project allow me to try to set up a translation status of Fedora, which was never done before <3
Is this the way you want me to report issues?

**Comment by nijel** [comment]
Yes, I've done real world testing only on projects on Hosted Weblate, so definitely more real world testing and feedback is useful. Still the main motivation for translation-finder was to ease setup and human interaction is expected in the end - the detection can never be absolutely accurate.
