### ISSUE TITLE
false positive with libmaxminddb-1.2.0

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#11]
Hello, while working on this: https://pagure.io/fedora-localization-statistics

I notice false positives with libmaxminddb-1.2.0
```
[
   {
      'filemask':'t/.deps/*.Po',
      'file_format':'po'
   }
]
```

The *.Po file inside .deps looks like dev thing.

Files: [files.txt](https://github.com/WeblateOrg/translation-finder/files/3125430/files.txt)

Upstream sources: https://github.com/maxmind/libmaxminddb/releases

Thanks a lot for your help!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Jibec** [comment]
here is an idea of the impact fixing this issue: https://pagure.io/fedora-localization-statistics/c/0ab77efbb7b3ba7827782dd3e1c28ae2315efc07?branch=master
