### ISSUE TITLE
false positives with gnome-desktop3-3.32.1

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#12]
Hello, while working on this: https://pagure.io/fedora-localization-statistics

I notice false positives with gnome-desktop3-3.32.1

```
[
   {
      'filemask':'desktop-docs/fdl/*/*.po',
      'file_format':'po'
   },
   {
      'filemask':'desktop-docs/gpl/*/*.po',
      'file_format':'po'
   },
   {
      'filemask':'desktop-docs/gpl/*/sr@latin.po',
      'file_format':'po'
   },
   {
      'filemask':'desktop-docs/gpl/sr/*.po',
      'file_format':'po'
   },
   {
      'filemask':'desktop-docs/lgpl/*/*.po',
      'file_format':'po'
   },
   {
      'filemask':'po/*.po',
      'file_format':'po'
   },
   {
      'filemask':'po/*.po',
      'template':'po/en.po',
      'file_format':'po-mono'
   }
]
```

these match are false positives:
* 'filemask':'desktop-docs/gpl/*/sr@latin.po',
* 'filemask':'desktop-docs/gpl/sr/*.po',

There may be something weird with the way the gnome team handle Serbian language:
```
$ find . | grep sr
./desktop-docs/gpl/sr
./desktop-docs/gpl/sr/sr@latin.po
./desktop-docs/gpl/sr/sr.po
./desktop-docs/gpl/sr@latin
./desktop-docs/gpl/sr@latin/sr@latin.po
./po/sr@latin.po
./po/sr.po
```

thanks a lot for your help!

**Comment by nijel** [comment]
Hmm, this is really weird. IMHO `./desktop-docs/gpl/sr/sr@latin.po` should not be there, the rest would be then simply `./desktop-docs/gpl/*/*.po`. Still we probably don't handle correctly the `@latin` suffix.

**Comment by Jibec** [comment]
fine for a wontfix for now, I'll tell you what's the answer of gnome teams: https://mail.gnome.org/archives/gnome-i18n/2019-April/msg00040.html

I'll close it of needed

**Comment by Jibec** [comment]
fixed upstream https://gitlab.gnome.org/GNOME/gnome-desktop/merge_requests/37
