### ISSUE TITLE
Please add support for fluent

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#16]
hello Michal,

can you please add detection of fluent files created by Mozilla?

Announcement:https://hacks.mozilla.org/2019/04/fluent-1-0-a-localization-system-for-natural-sounding-translations/
Fluent project: https://projectfluent.org/

**Comment by nijel** [comment]
The problem here is that it's not supported by Weblate (see https://github.com/WeblateOrg/weblate/issues/1926) mostly because there is missing support in the translate-toolkit (see https://github.com/translate/translate/issues/3389).

Adding detection itself should be easy though.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Jibec** [comment]
thank you Michal, I already subscribed to these issues this morning ;)

for my usecase, I only need pocount to work with fluent, but I have no idea how difficult this is to work.

waiting for the translate toolkit to support this, I asked there how to do: https://github.com/projectfluent/python-fluent/issues/117 I assume I may use this to parse it as a json file and make my stat using this: https://github.com/projectfluent/python-fluent/blob/master/tools/parse.py
