### ISSUE TITLE
Implement .yaml in the discovery

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/translation-finder#17]
Improve the automatic discovery so it will recognize .yaml files.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
