### ISSUE TITLE
gnome-clock false positives

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#6]
Hello, while working on this! https://pagure.io/fedora-localization-statistics

I notice false positives with gnome-clocks-3.32.0

File list is: [files.txt](https://github.com/WeblateOrg/translation-finder/files/3119915/files.txt)

It finds this:
```
[
   {
      'filemask':'help/*/*.po',
      'file_format':'po'
   },
   {
      'filemask':'help/*/pt_BR.po',
      'file_format':'po'
   },
   {
      'filemask':'help/pt_BR/*.po',
      'file_format':'po'
   },
   {
      'filemask':'po/*.po',
      'file_format':'po'
   }
]
```

The two "pt_BR" are a bug.
I noticed the same bug with other gnome packages, let me know if you need a few more.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Jibec** [comment]
thank you @nijel noob question, how do I test it locally without waiting for a pip release?

**Comment by nijel** [comment]
You can install from git by pip. Either use local checkout and `pip install -e .` or remotely using `pip install git+https://github.com/WeblateOrg/translation-finder.git@master`.

**Comment by Jibec** [comment]
you should change your nickname into **magic-nijel** 💟
