### ISSUE TITLE
chkconfig-1.11 false positives

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#7]
Hello, while working on this! https://pagure.io/fedora-localization-statistics

I notice false positives with chkconfig-1.11

File list is: [files.txt](https://github.com/WeblateOrg/translation-finder/files/3122094/files.txt)

It finds this:
```
[
   {
      'name':'chkconfig.default',
      'filemask':'po/*.po',
      'new_base':'po/chkconfig.pot',
      'file_format':'auto'
   },
   {
      'filemask':'po/*.po',
      'new_base':'po/chkconfig.pot',
      'file_format':'po'
   }
]
```

I feel like the name':'chkconfig.default' is a bug, is it?

**Comment by nijel** [comment]
That's probably imported from transifex configuration, look for `.tx` files.

**Comment by nijel** [comment]
It's coming from there: https://github.com/fedora-sysv/chkconfig/blob/master/.tx/config

**Comment by nijel** [comment]
So this is actually expected behavior to import Transifex configuration.

**Comment by Jibec** [comment]
ok, so everytime I have an "auto", it means it's discovered from transifex config?

**Comment by nijel** [comment]
It means that it was discovered from transifex config and that it didn't specify format. But that shows another bug - the auto format is no longer present in Weblate...

**Comment by Jibec** [comment]
OK, let's close the issue then, thanks a lot ;)
